matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    image: rust:slim
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default $RUST
      - cargo clippy
      - cargo test
