name: Cross Compile

on:
  push:
    branches:
      - release
  # pull_request:
  #   branches:
  #     - main
  #     - master

jobs:
  cross-compile:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu # Linux 64-bit
          - aarch64-unknown-linux-gnu # Linux ARM64
          - arm-unknown-linux-gnueabihf # Linux ARMv7 (Raspberry Pi)
          - x86_64-pc-windows-msvc # Windows 64-bit
          - x86_64-apple-darwin # macOS (nécessite un runner macOS)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }} # Installe la cible de compilation

      - name: Build release binary for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      # Optionnel : to archive binaries
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/${{ github.event.repository.name }} # adapt path/name
          # For Windows, add .exe:
          # path: target/${{ matrix.target }}/release/${{ github.event.repository.name }}${{ startsWith(matrix.target, 'x86_64-pc-windows') && '.exe' || '' }}
